// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package snowflake

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// SnowflakeClient is the client API for Snowflake service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SnowflakeClient interface {
	GetSnowflake(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*SnowflakeReply, error)
}

type snowflakeClient struct {
	cc grpc.ClientConnInterface
}

func NewSnowflakeClient(cc grpc.ClientConnInterface) SnowflakeClient {
	return &snowflakeClient{cc}
}

func (c *snowflakeClient) GetSnowflake(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*SnowflakeReply, error) {
	out := new(SnowflakeReply)
	err := c.cc.Invoke(ctx, "/snowflake.Snowflake/GetSnowflake", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SnowflakeServer is the server API for Snowflake service.
// All implementations must embed UnimplementedSnowflakeServer
// for forward compatibility
type SnowflakeServer interface {
	GetSnowflake(context.Context, *Empty) (*SnowflakeReply, error)
	mustEmbedUnimplementedSnowflakeServer()
}

// UnimplementedSnowflakeServer must be embedded to have forward compatible implementations.
type UnimplementedSnowflakeServer struct {
}

func (UnimplementedSnowflakeServer) GetSnowflake(context.Context, *Empty) (*SnowflakeReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSnowflake not implemented")
}
func (UnimplementedSnowflakeServer) mustEmbedUnimplementedSnowflakeServer() {}

// UnsafeSnowflakeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SnowflakeServer will
// result in compilation errors.
type UnsafeSnowflakeServer interface {
	mustEmbedUnimplementedSnowflakeServer()
}

func RegisterSnowflakeServer(s grpc.ServiceRegistrar, srv SnowflakeServer) {
	s.RegisterService(&_Snowflake_serviceDesc, srv)
}

func _Snowflake_GetSnowflake_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SnowflakeServer).GetSnowflake(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/snowflake.Snowflake/GetSnowflake",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SnowflakeServer).GetSnowflake(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _Snowflake_serviceDesc = grpc.ServiceDesc{
	ServiceName: "snowflake.Snowflake",
	HandlerType: (*SnowflakeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSnowflake",
			Handler:    _Snowflake_GetSnowflake_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/snowflake.proto",
}
